// <auto-generated />
using System;
using HiveQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveQ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116015541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HiveQ.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotificationId");

                    b.HasIndex("QueueEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HiveQ.Models.Queue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedWaitTimePerPerson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("QRCodeImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalServedToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueueId");

                    b.HasIndex("QRCodeData")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            QueueId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentQueueSize = 0,
                            Description = "Main service queue for morning hours",
                            EstimatedWaitTimePerPerson = 5,
                            IsActive = true,
                            MaxCapacity = 50,
                            QRCodeData = "HIVEQ_QUEUE_1",
                            QueueName = "Morning Service",
                            Status = "Active",
                            TotalServedToday = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HiveQ.Models.QueueEntry", b =>
                {
                    b.Property<int>("QueueEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedWaitTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueueEntryId");

                    b.HasIndex("QueueId");

                    b.HasIndex("UserId");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("HiveQ.Models.QueueHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaitTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoryId");

                    b.HasIndex("QueueEntryId")
                        .IsUnique();

                    b.HasIndex("QueueId");

                    b.HasIndex("UserId");

                    b.ToTable("QueueHistories");
                });

            modelBuilder.Entity("HiveQ.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CompanyAddress = "123 Main St, City, State 12345",
                            CompanyCategory = "Food & Beverage",
                            CompanyDescription = "A cozy coffee shop in the heart of the city",
                            CompanyName = "Sample Coffee Shop",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@coffeeshop.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Johnson",
                            PasswordHash = "hashed_password_here",
                            PhoneNumber = "5551234567"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@example.com",
                            FirstName = "John",
                            IsActive = true,
                            IsVerified = false,
                            LastName = "Doe",
                            PasswordHash = "hashed_password_here",
                            PhoneNumber = "5559876543"
                        });
                });

            modelBuilder.Entity("HiveQ.Models.Notification", b =>
                {
                    b.HasOne("HiveQ.Models.QueueEntry", "QueueEntry")
                        .WithMany("Notifications")
                        .HasForeignKey("QueueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveQ.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QueueEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiveQ.Models.Queue", b =>
                {
                    b.HasOne("HiveQ.Models.User", "User")
                        .WithMany("Queues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiveQ.Models.QueueEntry", b =>
                {
                    b.HasOne("HiveQ.Models.Queue", "Queue")
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveQ.Models.User", "User")
                        .WithMany("QueueEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiveQ.Models.QueueHistory", b =>
                {
                    b.HasOne("HiveQ.Models.QueueEntry", "QueueEntry")
                        .WithOne("QueueHistory")
                        .HasForeignKey("HiveQ.Models.QueueHistory", "QueueEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiveQ.Models.Queue", "Queue")
                        .WithMany("QueueHistories")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveQ.Models.User", "User")
                        .WithMany("QueueHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("QueueEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiveQ.Models.Queue", b =>
                {
                    b.Navigation("QueueEntries");

                    b.Navigation("QueueHistories");
                });

            modelBuilder.Entity("HiveQ.Models.QueueEntry", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("QueueHistory");
                });

            modelBuilder.Entity("HiveQ.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("QueueEntries");

                    b.Navigation("QueueHistories");

                    b.Navigation("Queues");
                });
#pragma warning restore 612, 618
        }
    }
}
